name: Run Simulation

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-simulation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        lfs: true  # Ensures Git LFS files are pulled

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install coinstac-simulator
      run: sudo npm i -g coinstac-simulator

    - name: Build Docker image
      run: docker build -t avg_test_meshnet_no_wan .

    - name: Run the terminal simulator
      run: docker run avg_test_meshnet_no_wan
