name: Run Simulation

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-simulation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download COINSTAC AppImage
      run: wget https://github.com/trendscenter/coinstac/releases/download/v6.8.5/COINSTAC-6.8.5-linux.AppImage

    - name: Make COINSTAC AppImage executable
      run: chmod a+x COINSTAC-6.8.5-linux.AppImage

    - name: Run COINSTAC AppImage
      run: ./COINSTAC-6.8.5-linux.AppImage &
      # Run in background to continue with the next steps

    - name: Build Docker image
      working-directory: .
      run: docker build -t avg_test_meshnet_no_wan .

    - name: Run the terminal simulator
      run: coinstac-simulator
